---
name: "push"

on:
  release:
    types:
      - published

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - name: "Build:checkout"
        uses: actions/checkout@v2
      - name: "Build:buildx"
        uses: docker/setup-buildx-action@v1
      - name: "Build:login"
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: "Build:dockerimage"
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          file: Dockerfile.controller
          tags: ghcr.io/k6io/operator:latest,ghcr.io/k6io/operator:controller-${{ github.event.release.tag_name }}
      - name: "Build:dockerimage"
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          file: Dockerfile.runner
          tags: ghcr.io/k6io/operator:latest-runner,ghcr.io/k6io/operator:runner-${{ github.event.release.tag_name }}
      - name: "Build:dockerimage"
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          file: Dockerfile.starter
          tags: ghcr.io/k6io/operator:latest-starter,ghcr.io/k6io/operator:starter-${{ github.event.release.tag_name }}
