---
name: "push"

on:
  release:
    types:
      - published

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - name: "Build:checkout"
        uses: actions/checkout@v2
      - name: "Build:login"
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: "Build:dockerimage"
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile.controller
          tags: k6io/operator:latest,k6io/operator:controller-${{ github.event.release.tag_name }}
      - name: "Build:dockerimage"
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile.runner
          tags: k6io/operator:latest-runner,k6io/operator:runner-${{ github.event.release.tag_name }}
      - name: "Build:dockerimage"
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile.starter
          tags: k6io/operator:latest-starter,k6io/operator:starter-${{ github.event.release.tag_name }}
