---
name: Yaml Lint
on:
  - push
  - pull_request
jobs:
  lintAllTheThings:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: yaml-lint
        uses: ibiqlik/action-yamllint@v3
        with:
          extends: default
          rules:
            indentation: disable # kustomize can rewrite yaml files and break this rule
